'use client';

import { useCallback, useEffect, useState } from 'react';
import { Boxes, ChevronRight, Plus } from 'lucide-react';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/feedback';
import { CAMPAIGN_CHANNELS, CAMPAIGN_CHANNEL_LABELS, CAMPAIGN_STATUSES, CAMPAIGN_STATUS_LABELS, type CampaignStatus } from '@/lib/campaign/schema';

type StrategySummary = { objectives: string[]; channelCount: number; hasKPIs: boolean } | null;
type CampaignStrategy = { id: string; title: string; version: number; status: string; isPrimary: boolean; sortOrder: number; outputSummary: StrategySummary };
export type Campaign = { id: string; name: string; objective: string | null; description: string | null; status: CampaignStatus; startDate: string | null; endDate: string | null; budget: number | null; currency: string; channels: string[]; channelSpecification: string | null; clientId: string | null; strategyId: string | null; strategy: CampaignStrategy | null; strategies: CampaignStrategy[]; createdAt: string; updatedAt: string; contentCount?: number };
type StrategyOption = { id: string; title: string; version: number; status: string };
type ListData = { campaigns: Campaign[]; total: number; strategyOptions: StrategyOption[]; canManage: boolean; gate: { hasApprovedStrategy: boolean } };

export function statusTone(status: CampaignStatus): string { if (status === 'ACTIVE' || status === 'COMPLETED') return 'tone-good'; if (status === 'PLANNED') return 'tone-info'; return 'tone-muted'; }
function timeAgo(iso: string): string { const seconds = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000)); if (seconds < 60) return 'just now'; const minutes = Math.round(seconds / 60); if (minutes < 60) return `${minutes}m ago`; const hours = Math.round(minutes / 60); if (hours < 24) return `${hours}h ago`; const days = Math.round(hours / 24); if (days < 30) return `${days}d ago`; return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); }
function formatBudget(value: number | null, currency: string): string { if (value === null) return 'Not set'; try { return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(value); } catch { return `${value.toLocaleString('en-US')} ${currency}`; } }

export function CampaignStudio({ brandId, brandName }: { brandId: string; brandName: string }) {
  const [data, setData] = useState<ListData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [statusFilter, setStatusFilter] = useState(''); const [channelFilter, setChannelFilter] = useState(''); const [query, setQuery] = useState('');
  const load = useCallback(async () => { setError(null); try { const params = new URLSearchParams(); if (statusFilter) params.set('status', statusFilter); if (channelFilter) params.set('channel', channelFilter); if (query) params.set('q', query); const encoded = params.toString(); const response = await fetch(`/api/brands/${brandId}/campaigns${encoded ? `?${encoded}` : ''}`, { cache: 'no-store' }); if (response.status === 401) { window.location.href = '/login'; return; } const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || 'Could not load campaigns'); setData(body); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load campaigns'); } finally { setLoading(false); } }, [brandId, statusFilter, channelFilter, query]);
  useEffect(() => { load(); }, [load]);
  const canCreate = Boolean(data?.gate.hasApprovedStrategy);
  const createHref = `/brands/${brandId}/campaigns/new`;

  return <div className="grid" style={{ gap: 16 }}>
    <div className="card"><div className="section-title" style={{ flexWrap: 'wrap', gap: 10 }}><div><div className="eyebrow">Campaigns</div><h2 style={{ margin: '5px 0' }}>{brandName} campaign workspace</h2></div><div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}><a href={createHref} className="badge auth-submit" style={{ display: 'inline-flex', textDecoration: 'none', opacity: canCreate ? 1 : 0.55, pointerEvents: canCreate ? 'auto' : 'none' }} aria-disabled={!canCreate}><Plus size={14} /> New campaign</a></div></div><p className="subtitle" style={{ marginTop: 0 }}>Plan and run campaigns grounded in one or more approved strategies — budget, dates, channels and lifecycle.</p><div className="content-filters" style={{ marginTop: 14 }}><input className="content-filter-input" placeholder="Search by name…" value={query} onChange={(event) => setQuery(event.target.value)} style={{ minWidth: 180 }} /><select className="content-filter-select" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="">All statuses</option>{CAMPAIGN_STATUSES.map((status) => <option key={status} value={status}>{CAMPAIGN_STATUS_LABELS[status]}</option>)}</select><select className="content-filter-select" value={channelFilter} onChange={(event) => setChannelFilter(event.target.value)}><option value="">All channels</option>{CAMPAIGN_CHANNELS.map((channel) => <option key={channel} value={channel}>{CAMPAIGN_CHANNEL_LABELS[channel]}</option>)}</select></div></div>
    {!canCreate && !loading && !error ? <div className="card" style={{ borderColor: 'rgba(139,124,255,.35)' }}><div style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}><span className="status-dot" style={{ background: 'var(--accent-2)', marginTop: 5, flexShrink: 0 }} /><div><div className="activity-title">Campaigns need an approved strategy</div><p className="activity-meta" style={{ marginTop: 6, lineHeight: 1.5, maxWidth: 720 }}>Campaigns are grounded in approved strategy versions for {brandName}. Generate and approve a strategy to unlock campaign planning.</p><a className="badge" href={`/brands/${brandId}?view=strategy`} style={{ display: 'inline-flex', marginTop: 10, textDecoration: 'none' }}>Open Strategy →</a></div></div></div> : null}
    {error ? <div className="card" style={{ borderColor: 'rgba(239,68,68,.35)' }}><ErrorState message={error} /></div> : null}
    {loading ? <LoadingState label="Loading campaigns…" /> : error ? null : !data || data.campaigns.length === 0 ? <EmptyState title="No campaigns yet" description="Create a campaign grounded in one or more approved strategies — add objectives, budget, dates and channels, then move it into planning." action={canCreate && data?.canManage ? <a href={createHref} className="badge auth-submit" style={{ display: 'inline-flex', textDecoration: 'none' }}><Plus size={14} /> New campaign</a> : undefined} /> : <div className="grid" style={{ gap: 12 }}>{data.campaigns.map((campaign) => <a className="card hover-lift content-item" href={`/brands/${brandId}/campaigns/${campaign.id}`} key={campaign.id}><div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div style={{ minWidth: 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}><span className="status-dot" style={{ background: campaign.status === 'ACTIVE' ? 'var(--accent)' : campaign.status === 'COMPLETED' || campaign.status === 'PLANNED' ? 'var(--accent-2)' : 'var(--muted)', marginTop: 1 }} /><span className="activity-title">{campaign.name}</span></div><div className="content-filters" style={{ marginTop: 8 }}><span className={`badge ${statusTone(campaign.status)}`}>{CAMPAIGN_STATUS_LABELS[campaign.status]}</span>{campaign.strategies.length > 0 ? <span className="chip">{campaign.strategies.length} strateg{campaign.strategies.length === 1 ? 'y' : 'ies'}</span> : null}{campaign.strategy ? <span className="chip">Primary v{campaign.strategy.version}</span> : null}{campaign.channels.length > 0 ? <span className="chip">{campaign.channels.length} channel{campaign.channels.length === 1 ? '' : 's'}</span> : null}{campaign.budget !== null ? <span className="chip">{formatBudget(campaign.budget, campaign.currency)}</span> : null}</div></div><ChevronRight size={16} color="var(--muted)" style={{ flexShrink: 0 }} /></div><div className="content-item-footer"><span className="activity-meta" style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Boxes size={13} /> {campaign.contentCount ?? 0} content item{campaign.contentCount === 1 ? '' : 's'}</span><span className="activity-meta">Created {timeAgo(campaign.createdAt)}</span></div></a>)}{data.total > data.campaigns.length ? <p className="activity-meta" style={{ textAlign: 'center', margin: 0, padding: 8 }}>Showing {data.campaigns.length} of {data.total}. Refine filters to narrow results.</p> : null}</div>}
  </div>;
}
