'use client';
import { useEffect, useState } from 'react';
import { BookOpen, Save, Users } from 'lucide-react';
import { ThemeController } from '@/components/theme/theme-controller';
import { ErrorState, LoadingState } from '@/components/ui/feedback';

type Workspace={id:string;name:string;workspace_type:'AGENCY'|'BUSINESS';timezone:string|null};

export function SettingsClient(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null),[name,setName]=useState(''),[type,setType]=useState<'AGENCY'|'BUSINESS'>('AGENCY'),[timezone,setTimezone]=useState('UTC'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/workspace',{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b?.error||'Could not load workspace');return b;}).then(b=>{setWorkspace(b.workspace);setName(b.workspace.name);setType(b.workspace.workspace_type);setTimezone(b.workspace.timezone||'UTC');}).catch(e=>setError(e instanceof Error?e.message:'Could not load workspace')).finally(()=>setLoading(false));},[]);
 async function save(){setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/workspace',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name,workspaceType:type,timezone})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||'Could not save workspace');setWorkspace(b.workspace);setMessage('Workspace settings saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save workspace');}finally{setSaving(false);}}
 if(loading)return <LoadingState label="Loading workspace settings…"/>;
 return <main className="main"><div className="topbar"><div><div className="eyebrow">Settings</div><h1>Workspace & preferences</h1><p className="subtitle">Keep the workspace identity, timezone and visual comfort under your control.</p></div></div>{error&&<ErrorState message={error}/>}<div className="settings-grid"><section className="card"><div className="section-title"><div><div className="eyebrow">Workspace</div><h2>Workspace identity</h2></div></div><label>Workspace name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Workspace type<select value={type} onChange={e=>setType(e.target.value as 'AGENCY'|'BUSINESS')}><option value="AGENCY">Agency — multiple brands</option><option value="BUSINESS">Business — primarily your own brand</option></select></label><label>Timezone<select value={timezone} onChange={e=>setTimezone(e.target.value)}><option>UTC</option><option>Asia/Kolkata</option><option>America/New_York</option><option>Europe/London</option><option>Asia/Singapore</option><option>Asia/Tokyo</option></select><small className="field-help">Used for schedules, campaign dates and reporting day boundaries.</small></label><button type="button" className="badge auth-submit" onClick={save} disabled={saving}><Save size={14}/>{saving?'Saving…':'Save workspace'}</button>{message&&<p className="field-note">{message}</p>}</section><section className="card"><div className="section-title"><div><div className="eyebrow">Appearance</div><h2>Theme</h2></div></div><p className="subtitle">Light is the default. Switch to dark or follow your operating system later.</p><ThemeController/><div style={{marginTop:18,display:'flex',gap:8,flexWrap:'wrap'}}><a className="badge" href="/settings/team"><Users size={14}/> Manage team</a><button type="button" className="badge" onClick={async()=>{await fetch('/api/tours',{method:'DELETE'});setMessage('Guides reset. Open the workflow pages again to replay them.');}}><BookOpen size={14}/> Replay guides</button></div></section></div>{workspace&&<p className="field-note">Workspace edits remain protected by Owner/Admin authorization.</p>}</main>;
}